# Generated by Django 5.2.4 on 2025-07-15 10:31

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=blog.models.profile_image_file_path
            ),
        ),
    ]
