# Generated by Django 5.2.4 on 2025-07-31 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.profile",
            ),
        ),
    ]
