# Generated by Django 5.2.4 on 2025-07-31 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.profile",
            ),
        ),
    ]
