# Generated by Django 5.2.4 on 2025-07-31 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_comment_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="profile",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="profile",
            new_name="author",
        ),
    ]
