# Generated by Django 5.2.4 on 2025-08-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_follow_like_alter_comment_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=1000),
        ),
    ]
