# Generated by Django 5.2.4 on 2025-08-12 16:25

import blog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_post_celery_task_id_post_published_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="blog_post_is_publ_96cac2_idx",
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_published",
        ),
        migrations.AlterField(
            model_name="post",
            name="scheduled_time",
            field=models.DateTimeField(
                blank=True, null=True, validators=[blog.models.validate_future_date]
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["status"], name="blog_post_status_02ce19_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["scheduled_time"], name="blog_post_schedul_8ce6bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["-created_at"], name="blog_profil_created_6bc67c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["user"], name="blog_profil_user_id_9164df_idx"),
        ),
    ]
